name: Create Pull Request from upstream

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, you can adjust this schedule

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full history is fetched
          ref: master

      - name: Setup Git
        run: |
          git config user.name 'MR Nim (Github Action)'
          git config user.email 'mr.nim94@gmail.com'

      - name: Add remote upstream
        run: git remote add upstream https://github.com/arunbandari/mongo-gui.git

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Checkout to a new branch
        run: |
          BRANCH_NAME="update-upstream-$(date +'%Y-%m-%d-%H-%M-%S')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Merge changes
        run: |
          git merge --no-edit upstream/master

      - name: Push to GitHub
        run: git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: Update from upstream
          title: 'Sync with upstream'
          body: 'Updating the repository with changes from upstream'
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          labels: sync,automated pr
